Empresa/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.urls import include, path
from django.conf import settings


from django.contrib.auth import views as auth_views


urlpatterns = [
	url(r'^admin/', admin.site.urls),

	url(r'^pri/', include ('apps.Index.urls')),
	url(r'^tra/', include ('apps.Trabajador.urls')),

	url(r'^$', auth_views.LoginView.as_view(template_name='Empresa/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='Empresa/login.html'), name='logout'),
	path('accounts/', include('allauth.urls')),
	url(r'^oauth/', include('social_django.urls', namespace='social')),
]


if settings.DEBUG:
	from django.conf.urls.static import static
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Index/urls.py
from django.conf.urls import url, include
from apps.Index.views import index, RegistroUsuario,Cliente_List,formulario_view,EditarCliente,EliminarCliente,Cliente_List2,AsignarTecnicoU

from django.urls import include, path

app_name = "index";

urlpatterns = [
url(r'^$', index,name='Menu'),
url(r'^registrar$', RegistroUsuario.as_view()),
url(r'^clientes$', Cliente_List, name='Clientes'),
url(r'^nuevo$', formulario_view, name='Crear_Cliente'),
path('editarCliente/<int:id>' ,EditarCliente, name='EditarCliente'),
path('eliminarCliente/<int:id>' ,EliminarCliente, name='EliminarCliente'),
url(r'^asignaciones$', Cliente_List2, name='Asignaciones'),
path('asignar/<int:id>' ,AsignarTecnicoU, name='AsignarTecnico'),
]

apps/Trabajador/urls.py
from django.conf.urls import url, include
from apps.Trabajador.views import VerClientes,RealizarOrden,VerOrdenes

from django.urls import include, path

app_name = "trabajador";

urlpatterns = [
url(r'^clientes$', VerClientes, name='Clientes'),
path('orden/<int:id>' ,RealizarOrden, name='Orden'),
url(r'^orden_realizadas$', VerOrdenes, name='Realizadas'),
]

templates/Empresa/asignaciones.html
{% extends 'base/base.html' %}

{% block content %}

{% if user.is_staff %}
{% block navbar %}
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <nav class="navbar navbar-default">
          <div class="container-fluid" >
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index:Menu' %}">INICIO</a>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Clientes' %}">CLIENTES</a>
                </div>

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Asignaciones' %}">ASIGNAR</a>
                </div>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">OPCIONES<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}">SALIR</a></li>
                        </ul>
                    </li>
                </ul>

              </div>


          </div>
        </nav>
      </div>
    </div>
  </div>
</div>



<table class="table table-bordered" style="font-size:20px;margin-left: 5%;margin-right: 5%; width: 90%; border: 2px solid;">
  <thead>
    <tr>
      <td style="border:2px solid;">Nombres</td>
      <td style="border:2px solid;">Direccion</td>
      <td style="border:2px solid;">Ciudad</td>
      <td style="border:2px solid;">Comuna</td>
      <td style="border:2px solid;">Telefono</td>
      <td style="border:2px solid;">Email</td>
      <td style="border:2px solid;">Accion</td>
    </tr>
  </thead>

  <tbody>

<div align="center">
  <h1> ASIGNAR TECNICOS A CLIENTES </h1>
</div>
<br>

    {% if clientes %}
    {% for cliente in clientes %}
    <tr>
      <td style="border:2px solid;"><center>{{ cliente.nombre }}</center></td>
      <td style="border:2px solid;"><center>{{ cliente.direccion }}</center></td>
      <td style="border:2px solid;"><center>{{ cliente.ciudad }}</center></td>
      <td style="border:2px solid;"><center>{{ cliente.comuna }}</center></td>
      <td style="border:2px solid;"><center>{{ cliente.telefono }}</center></td>
      <td style="border:2px solid;"><center>{{ cliente.correo }}</center></td>
      <td style="border:2px solid;">
        <center><a class="btn btn-primary" href="{% url 'index:AsignarTecnico' cliente.id %}">&nbsp;&nbsp;ASIGNAR&nbsp;&nbsp;</a></center>
      </td>
    </tr>
    {% endfor %}
    {% else %}

    <h1>No hay clientes </h1>

    {% endif %}

  </tbody>

</table>

{% endblock %}
{% endif %}



{% endblock %}

templates/Empresa/asignar_tecnico.html
{% extends 'base/base.html' %}

{% block content %}

{% if user.is_staff %}
{% block navbar %}
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <nav class="navbar navbar-default">
          <div class="container-fluid" >
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index:Menu' %}">INICIO</a>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Clientes' %}">CLIENTES</a>
                </div>

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Asignaciones' %}">ASIGNAR</a>
                </div>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">OPCIONES<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}">SALIR</a></li>
                        </ul>
                    </li>
                </ul>

              </div>


          </div>
        </nav>
      </div>
    </div>
  </div>
</div>




<div align="center">
  <h1> Asignar Tecnico </h1>
</div>

<form method="POST" style="margin:20px 100px" enctype="multipart/form-data">

  {% csrf_token %}
  <h1>Datos del cliente</h1>
<div style="border: 2px solid; padding: 20px">
<h2>Nombre</h2>
  {{ form.nombre }}
<h2>Direccion</h2>  
  {{ form.direccion }}
<h2>Ciudad</h2>
  {{ form.ciudad }}
<h2>Comuna</h2>
  {{ form.comuna }}
<h2>Telefono</h2>
  {{ form.telefono }}
<h2>Correo</h2>
  {{ form.correo }}
</div>

<h2>Asignar Tecnico</h2>
  {{ form.usuario }}
<br> 
<br>
<button type="submit" class="btn btn-primary btn-block btn-success"> REGISTRAR</button>
</form>





{% endblock %}
{% endif %}



{% endblock %}

templates/Empresa/clientes.html
{% extends 'base/base.html' %}

{% block content %}

{% if user.is_staff %}
{% block navbar %}
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <nav class="navbar navbar-default">
          <div class="container-fluid" >
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index:Menu' %}">INICIO</a>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Clientes' %}">CLIENTES</a>
                </div>

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Asignaciones' %}">ASIGNAR</a>
                </div>

                <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">

                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">OPCIONES<span class="caret"></span></a>

                    <ul class="dropdown-menu" role="menu">
                      <li><a href="{% url 'logout' %}">SALIR</a></li>
                    </ul>

                  </li>
                </ul>

              </div>
          </div>
        </nav>
      </div>
    </div>
  </div>
</div>

<a class="btn btn-primary" href="{% url 'index:Crear_Cliente' %}" style="margin-left: 5%;margin-bottom: 10px; background-color: #4287f5;">AGREGAR NUEVO CLIENTE</a>

<table class="table table-bordered" style="margin-left: 5%;margin-right: 5%; width: 90%; font-size: 20px; border: 2px solid;">
  <thead>
    <tr>
      <td style="border:2px solid;">Nombres</td> 
      <td style="border:2px solid;">Dirección</td>
      <td style="border:2px solid;">Ciudad</td>
      <td style="border:2px solid;">Comuna</td>
      <td style="border:2px solid;">Teléfono</td>
      <td style="border:2px solid;">Email</td>
      <td style="border:2px solid;">Acción</td>
    </tr>
  </thead>

  <tbody>

<div align="center">
  <h1> LISTA DE CLIENTES </h1>
</div>
<br>

    {% if clientes %}
    {% for cliente in clientes %}
    <tr>
      <td style="border:2px solid;"><center>{{ cliente.nombre }}</center></td>
      <td style="border:2px solid;"><center>{{ cliente.direccion }}</center></td>
      <td style="border:2px solid;"><center>{{ cliente.ciudad }}</center></td>
      <td style="border:2px solid;"><center>{{ cliente.comuna }}</center></td>
      <td style="border:2px solid;"><center>{{ cliente.telefono }}</center></td>
      <td style="border:2px solid;"><center>{{ cliente.correo }}</center></td>
      <td style="border:2px solid;">
        <center><a class="btn btn-primary" href="{% url 'index:EditarCliente' cliente.id %}">&nbsp;&nbsp;EDITAR&nbsp;&nbsp;</a></center>
        <br>
        <center><a class="btn btn-primary" href="{% url 'index:EliminarCliente' cliente.id %}" style="background-color: red;">ELIMINAR</a></center>
      </td>
    </tr>
    {% endfor %}
    {% else %}

    <h1>No hay clientes </h1>

    {% endif %}

  </tbody>

</table>

{% endblock %}
{% endif %}



{% endblock %}

templates/Empresa/eliminar_cliente.html
{% extends 'base/base.html' %}

{% block content %}

{% if user.is_staff %}
{% block navbar %}
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <nav class="navbar navbar-default">
          <div class="container-fluid" >
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index:Menu' %}">INICIO</a>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Clientes' %}">CLIENTES</a>
                </div>

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Asignaciones' %}">ASIGNAR</a>
                </div>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">OPCIONES<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}">SALIR</a></li>
                        </ul>
                    </li>
                </ul>

              </div>


          </div>
        </nav>
      </div>
    </div>
  </div>
</div>


<div align="center">
  <h1>ELIMINAR CLIENTE</h1>
</div>


<form method="post" style="margin:20px 100px" enctype="multipart/form-data">

  {% csrf_token %}

  <h3> ¿Quieres eliminar el cliente {{ cliente.nombre }} </h3>
  
  <button class="btn btn-primary btn-block btn-success" type="submit">Eliminar</button>
  <a class="btn btn-primary btn-block" href="{% url 'index:Clientes' %}">VOLVER</a>

</form>




{% endblock %}
{% endif %}



{% endblock %}

templates/Empresa/index.html
{% extends 'base/base.html' %}

{% block content %}

{% if user.is_staff %}
{% block navbar %}
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <nav class="navbar navbar-default">
          <div class="container-fluid" >
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index:Menu' %}">INICIO</a>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Clientes' %}">CLIENTES</a>
                </div>

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Asignaciones' %}">ASIGNAR</a>
                </div>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">OPCIONES<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}">SALIR</a></li>
                        </ul>
                    </li>
                </ul>

              </div>


          </div>
        </nav>
      </div>
    </div>
  </div>
</div>

<div style="width: 100%;">

  <center>
    <h1>ADMINISTRADOR</h1>
  </center>

  <div>
    <center><img src="/static/img/admin.png" alt="Logotipo" width="300px" border="0" style="border-radius: 300px; margin-bottom: 20px"></center>
    <center><h1 style="margin-top: -20px;">{{ user.username }}</h1></center>
  </div>

  <div>
      <br>
      <br>
      <center><a class="btn btn-primary" href="{% url 'index:Clientes' %}" style="font-size: 30px; margin-bottom: 10px; width: 300px; height: 50px; background-color: #4287f5;">CLIENTES</a></center>
      <center><a class="btn btn-primary" href="{% url 'index:Asignaciones' %}" style="font-size: 30px; margin-bottom: 10px;width: 300px; height:50px; background-color: #34c94b">ASIGNACIONES</a></center>
      <br>
  </div>

  

</div>


{% endblock %}

{% else %}
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <nav class="navbar navbar-default">
          <div class="container-fluid" >
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index:Menu' %}">INICIO</a>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'trabajador:Clientes' %}">CLIENTES</a>
                </div>

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Menu' %}"></a>
                </div>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">OPCIONES<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}">SALIR</a></li>
                        </ul>
                    </li>
                </ul>

              </div>


          </div>
        </nav>
      </div>
    </div>
  </div>
</div>

<div style="width: 100%;">

  <center>
    <h1>TRABAJADOR</h1>
  </center>

  <div>
    <center><img src="/static/img/usuario.png" alt="Logotipo" width="300px" border="0" style="border-radius: 300px; margin-bottom: 20px"></center>
    <center><h1 style="margin-top: -20px;">{{ user.first_name }}&ensp;{{ user.last_name }}</h1></center>
  </div>

  <div>
      <br>
      <br>
      <center><a class="btn btn-primary" href="{% url 'trabajador:Clientes' %}" style="font-size: 30px; margin-bottom: 10px; width: 300px; height: 50px; background-color: #A09E9E;">CLIENTES</a></center>

      <center><a class="btn btn-primary" href="{% url 'trabajador:Realizadas' %}" style="font-size: 30px; margin-bottom: 10px; width: 300px; height: 50px; background-color: #A09E9E;">VER ORDENES</a></center>
  </div>

</div>


{% endif %}

{% endblock %}

templates/Empresa/orden.html
{% extends 'base/base.html' %}

{% block content %}
{% block navbar %}
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <nav class="navbar navbar-default">
          <div class="container-fluid" >
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index:Menu' %}">INICIO</a>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Menu' %}">CLIENTES</a>
                </div>

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Menu' %}"></a>
                </div>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">OPCIONES<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}">SALIR</a></li>
                        </ul>
                    </li>
                </ul>

              </div>


          </div>
        </nav>
      </div>
    </div>
  </div>
</div>


<div align="center">
  <h1 style="font-family: times;" > REALIZAR ORDEN </h1>
</div>

<form method="POST" style="margin:20px 100px" enctype="multipart/form-data">

  {% csrf_token %}
<h2>Nombre del cliente</h2>
  {{ form.nombre }}
<h2>fecha de la orden</h2>  
  {{ form.fecha }}
<h2>Hora de Inicio</h2>
  {{ form.horainicio }}
<h2>Hora de Termino</h2>
  {{ form.horafin }}
<h2>Modelo del Ascensor</h2>
  {{ form.modeloascensor }}
<h2>Fallas Detectadas</h2>
  {{ form.fallasdetectadas }}
<h2>Reparaciones Efectuadas</h2>
  {{ form.reparacionesefectuadas }}
<h2>Piezas Cambiadas</h2>
  {{ form.cambiopiezas}}
<br>
<button type="submit" class="btn btn-primary btn-block btn-success"> REGISTRAR NUEVA ORDEN</button>
<a class="btn btn-primary btn-block" href="{% url 'trabajador:Clientes' %}" >VOLVER</a>
</form>







{% endblock %}
{% endblock %}

templates/Empresa/ordenes_realizadas.html
{% extends 'base/base.html' %}

{% block content %}
{% block navbar %}
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <nav class="navbar navbar-default">
          <div class="container-fluid" >
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index:Menu' %}">INICIO</a>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Menu' %}">CLIENTES</a>
                </div>

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Menu' %}"></a>
                </div>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">OPCIONES<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}">SALIR</a></li>
                        </ul>
                    </li>
                </ul>

              </div>


          </div>
        </nav>
      </div>
    </div>
  </div>
</div>



<table class="table table-bordered" style="font-size: 20px; margin-left: 5%;margin-right: 5%; width: 90%; border: 2px solid;">
	<thead>
		<tr>

			<td style="border:2px solid;"><center>Nombres</center></td>
			<td style="border:2px solid;"><center>Fecha</center></td>
			<td style="border:2px solid;"><center>Hora de inicio</center></td>
			<td style="border:2px solid;"><center>Hora de termino</center></td>
			<td style="border:2px solid;"><center>Modelo del ascensor</center></td>
			<td style="border:2px solid;"><center>Fallas detectadas</center></td>
			<td style="border:2px solid;"><center>Reparaciones efectuadas</center></td>
      <td style="border:2px solid;"><center>Piezas cambiadas</center></td>
      

		</tr>
	</thead>

	<tbody>

<div align="center">
	<h1> TUS CLIENTES ASIGNADOS </h1>
</div>
<br>

		{% if Info %}
		{% for informacion in Info %}


		<tr>
			<td style="border:2px solid;"><center>{{ informacion.nombre }}</center></td>
			<td style="border:2px solid;"><center>{{ informacion.fecha }}</center></td>
			<td style="border:2px solid;"><center>{{ informacion.horainicio }}</center></td>
			<td style="border:2px solid;"><center>{{ informacion.horafin }}</center></td>
			<td style="border:2px solid;"><center>{{ informacion.modeloascensor }}</center></td>
			<td style="border:2px solid;"><center>{{ informacion.fallasdetectadas }}</center></td>
			<td style="border:2px solid;"><center>{{ informacion.reparacionesefectuadas }}</center></td>
      <td style="border:2px solid;"><center>{{ informacion.cambiopiezas }}</center></td>

		</tr>

		{% endfor %}
		{% endif %}

	</tbody>
</table>






{% endblock %}
{% endblock %}

templates/Empresa/registrar_cliente.html
{% extends 'base/base.html' %}

{% block content %}

{% if user.is_staff %}
{% block navbar %}
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <nav class="navbar navbar-default">
          <div class="container-fluid" >
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index:Menu' %}">INICIO</a>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Clientes' %}">CLIENTES</a>
                </div>

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Asignaciones' %}">ASIGNAR</a>
                </div>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">OPCIONES<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}">SALIR</a></li>
                        </ul>
                    </li>
                </ul>

              </div>


          </div>
        </nav>
      </div>
    </div>
  </div>
</div>



<div align="center">
  <h1 style="font-family: times;" > REGISTRAR CLIENTE </h1>
</div>

<form method="post" style="margin:20px 100px">

  {% csrf_token %}

  {{ form.as_p }}
<br>
  <button type="submit" class="btn btn-primary"> REGISTRAR</button>
  <a class="btn btn-primary" href="{% url 'index:Clientes' %}">VOLVER</a>

</form>



{% endblock %}
{% endif %}



{% endblock %}

templates/Empresa/ver_clientes.html
{% extends 'base/base.html' %}

{% block content %}
{% block navbar %}
<div class="bs-docs-section clearfix">
  <div class="row">
    <div class="col-lg-12">
      <div class="bs-component">
        <nav class="navbar navbar-default">
          <div class="container-fluid" >
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index:Menu' %}">INICIO</a>
              </div>

              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Menu' %}">CLIENTES</a>
                </div>

                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'index:Menu' %}"></a>
                </div>

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">OPCIONES<span class="caret"></span></a>

                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}">SALIR</a></li>
                        </ul>
                    </li>
                </ul>

              </div>


          </div>
        </nav>
      </div>
    </div>
  </div>
</div>



<table class="table table-bordered" style="font-size: 20px; margin-left: 5%;margin-right: 5%; width: 90%; border: 2px solid;">
	<thead>
		<tr>

			<td style="border:2px solid;"><center>Nombres</center></td>
			<td style="border:2px solid;"><center>Direccion</center></td>
			<td style="border:2px solid;"><center>Ciudad</center></td>
			<td style="border:2px solid;"><center>Comuna</center></td>
			<td style="border:2px solid;"><center>Telefono</center></td>
			<td style="border:2px solid;"><center>Correo</center></td>
			<td style="border:2px solid;"><center>Accion</center></td>

		</tr>
	</thead>

	<tbody>

<div align="center">
	<h1> TUS CLIENTES ASIGNADOS </h1>
</div>
<br>

		{% if Info %}
		{% for informacion in Info %}


		<tr>
			<td style="border:2px solid;"><center>{{ informacion.nombre }}</center></td>
			<td style="border:2px solid;"><center>{{ informacion.direccion }}</center></td>
			<td style="border:2px solid;"><center>{{ informacion.ciudad }}</center></td>
			<td style="border:2px solid;"><center>{{ informacion.comuna }}</center></td>
			<td style="border:2px solid;"><center>{{ informacion.telefono }}</center></td>
			<td style="border:2px solid;"><center>{{ informacion.correo }}</center></td>
			<td style="border:2px solid;">
				<center><a class="btn btn-primary" href="{% url 'trabajador:Orden' informacion.id %}">REALIZAR ORDEN</a></center>
			</td>
		</tr>

		{% endfor %}
		{% endif %}

	</tbody>
</table>






{% endblock %}
{% endblock %}